org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Legacy Fabric 1.12.2 target
minecraft_version=1.12.2
yarn_mappings=1.12.2+build.442
loader_version=1.9.4
legacy_fabric_api_version=1.10.0+1.12.2

maven_group=dev.starlightlegacy
archives_base_name=starlight-legacy
mod_version=0.1.0
loom_version=1.3-SNAPSHOT
