pluginManagement {
    repositories {
        maven {
            name = 'Legacy Fabric'
            url = 'https://maven.legacyfabric.net/'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'StarLight-Legacy'
